[ORG 0X7E00]

RUNOS:
MOV DH, 8
xor ax, ax

%define LOAD_PLACEHOLDER      0X9000  ; Reserves 22 bytes for sample string
%define CURRTEXT              0X9016  ; Reserves 15 bytes
%define PLACEHOLDER_LEN       0X9026  ; Reserves 2 bytes (Word)
%define CURRENTROW            0X9028  ; Reserves 1 byte
%define ENTERP                0X9029  ; Reserves 1 byte
%define CURRTEXTWRITTEN       0X902A  ; Reserves 512 bytes for typing buffer!
%define CURRIND               0X942A  ; Reserves 2 bytes (Word)
%define LEN                   0X942C  ; Reserves 2 bytes (Word)
%define OP                    0X942E
%define CURRTEXTLEN           0X9430  ; Reserves 1 byte
%define EXTRA_C               0X9431  ; Reserves 1 byte
%define CKP                   0X9432  ; Reserves 1 byte
%define VARTOSAVE             0X9433  ; Reserves 512 bytes for disk scratchpad!
%define CURRENT_FL            0X9633  ; Reserves 2 bytes for filename letters
%define SAVED_TEXT_LEN        0X9635  ; Reserves 2 bytes (Word) 
%define CURRENT_FILE_TYPE     0X9637  ; Reserves 1 byte
%define CURRENT_FILES_IN_SYS  0X9638  ; Reserves 1 byte
%define CURR_OPEN_FILE        0X9639  ; Reserves 2 bytes (Word)
%define RANDOM_INDEX          0X963B  ; Reserves 1 byte

; Calculator registers allocations
%define NUM                   0X963C  ; Reserves 4 bytes
%define NUM1                  0X9640  ; Reserves 4 bytes
%define CURRENT_CHARACTER     0X9644  ; Reserves 1 byte
%define FINAL                 0X9645  ; Reserves 4 bytes
%define REMAINDER             0X9649  ; Reserves 1 byte
%define MULTIPLA              0X964A  ; Reserves 1 byte
%define MULTIPLA1             0X964B  ; Reserves 1 byte
%define COUNT_DIVLOOP         0X964C  ; Reserves 1 byte
%define CURRENT_FORGE_NUM     0X964D  ; Reserves 2 bytes (Word)
%define POWER                 0X964F  ; Reserves 2 bytes (Word)
%define ALL_FINALITY          0X9651  ; Reserves 2 bytes (Word)
%define SAVED_POWER           0X9653  ; Reserves 2 bytes (Word)
%define ALL_FINALITY1         0X9655  ; Reserves 2 bytes (Word)
%define ROWS                  0X9657  ; Reserves 1 byte
%define COLS                  0X9658  ; Reserves 1 byte

MOV BYTE[LEN], 14
MOV BYTE[CURRTEXT], 'W'
MOV BYTE[CURRTEXT+1], 'E'
MOV BYTE[CURRTEXT+2], 'L'
MOV BYTE[CURRTEXT+3], 'C'
MOV BYTE[CURRTEXT+4], 'O'
MOV BYTE[CURRTEXT+5], 'M'
MOV BYTE[CURRTEXT+6], 'E'
MOV BYTE[CURRTEXT+7], ' '
MOV BYTE[CURRTEXT+8], 'T'
MOV BYTE[CURRTEXT+9], 'O'
MOV BYTE[CURRTEXT+10], ' '
MOV BYTE[CURRTEXT+11], 'O'
MOV BYTE[CURRTEXT+12], 'S'
MOV BYTE[CURRTEXT+13], '_'
MOV BYTE[CURRTEXT+14], '1'

JMP LOG_SYS
LABELS:
SHUTDOWN:
HLT
JMP SHUTDOWN

;SAMPLE PROGRAM
MATH:
CMP BYTE[OP], 'a'
JE SETUP_OP
CMP BYTE[OP], 's'
JE SUBTRACT
CMP BYTE[OP], 'm'
JE MULTIP 

SETUP_OP:
MOV BX, 0
MOV BYTE[OP],0
MOV BYTE[OP+1],0
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
MOV BX, 0
INPUT_LOOP:
MOV AH,0X00
INT 0X16
MOV AH, 0X0E
INT 0X10

MOV BYTE[NUM+BX], AL

CMP BX, 3
JBE INCREMENT_BXIN
JA NEXT_IN
INCREMENT_BXIN:
INC BX
JMP INPUT_LOOP
NEXT_IN:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
MOV BX, 0
IN_L:
MOV AH,0X00
INT 0X16
MOV AH, 0X0E
INT 0X10

MOV BYTE[NUM1+BX], AL

CMP BX, 3
JBE INCREMENT_BXIN1
JA LBX2
INCREMENT_BXIN1:
INC BX
JMP IN_L
LBX2:
MOV BX,0
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
LBX:
CMP BX, 3
JBE INC_BX
JA NEXT_NUM
INC_BX:
INC BX
SUB BYTE[NUM + BX], 0X30
JMP LBX
NEXT_NUM:
MOV BX, 0
LBX1:
CMP BX, 3
JBE INC_BX1
JA ADD_THEM
INC_BX1:
INC BX
SUB BYTE[NUM1 + BX], 0X30
JMP LBX1

ADD_THEM:
MOV BX, 4
MOV BYTE[REMAINDER],0
LOOP_BRADAR:
CMP BX, 1
JAE DECREMEN_BX
JB CONV
DECREMEN_BX:
DEC BX
MOV AL, BYTE[NUM+BX]
ADD AL, BYTE[NUM1+BX]
ADD AL, BYTE[REMAINDER]
MOV BYTE[FINAL+BX], AL
CMP AL, 10
JE SETAL0
JB LOOP_BRADAR
JA SET_ANY
NORM_SETTING:

JMP LOOP_BRADAR
SETAL0:
MOV AL, 0
MOV BYTE[REMAINDER],1
MOV BYTE[FINAL+BX], AL
JMP LOOP_BRADAR
SET_ANY:
SUB AL, 10
MOV BYTE[REMAINDER],1
MOV BYTE[FINAL+BX], AL
JMP LOOP_BRADAR


CONV:
MOV BX, 0
MOV BYTE[REMAINDER],0
XOR AX, AX
XOR BX, BX
XOR CX, CX
XOR DX, DX
MOV BYTE[NUM+0], 0
MOV BYTE[NUM+1], 0
MOV BYTE[NUM+2], 0
MOV BYTE[NUM+3], 0

MOV BYTE[NUM1+0], 0
MOV BYTE[NUM1+1], 0
MOV BYTE[NUM1+2], 0
MOV BYTE[NUM1+3], 0
MOV WORD[MULTIPLA], 0
MOV WORD[MULTIPLA1],0

LOOP_CONVERT:
ADD BYTE[FINAL+BX], 0X30
CMP BX, 3
JBE INCREMEN_BX
JA LOG_NUM
INCREMEN_BX:
INC BX
JMP LOOP_CONVERT
LOG_NUM:
;LOG MESSAGE
MOV BX, 0
MOV WORD[LEN], 3
A:
MOV AH, 0X0E
MOV AL,BYTE[FINAL+BX]
INT 0X10
ADD BX,1
CMP BX, WORD[LEN]
JBE A
JAE NEWLINE

SUBTRACT:
MOV BX, 0
MOV BYTE[OP],0
MOV BYTE[OP+1],0
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
MOV BX, 0
INPUT_LOOP1:
MOV AH,0X00
INT 0X16
MOV AH, 0X0E
INT 0X10

MOV BYTE[NUM+BX], AL

CMP BX, 3
JBE INCREMENT_BXIN11
JA NEXT_IN1
INCREMENT_BXIN11:
INC BX
JMP INPUT_LOOP1
NEXT_IN1:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
MOV BX, 0
IN_L1:
MOV AH,0X00
INT 0X16
MOV AH, 0X0E
INT 0X10

MOV BYTE[NUM1+BX], AL

CMP BX, 3
JBE INCREMENT_BXIN1Q
JA LBX21
INCREMENT_BXIN1Q:
INC BX
JMP IN_L1
LBX21:
MOV BX,0
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
LBXW:
CMP BX, 3
JBE INC_BX3
JA NEXT_NUM1
INC_BX3:
INC BX
SUB BYTE[NUM + BX], 0X30
JMP LBXW
NEXT_NUM1:
MOV BX, 0
LBX1Z:
CMP BX, 3
JBE INC_BX1111
JA SUB_THEM
INC_BX1111:
INC BX
SUB BYTE[NUM1 + BX], 0X30
JMP LBX1Z

SUB_THEM:
MOV BX, 4
MOV BYTE[REMAINDER],0
LOOP_BRADAR1:
CMP BX, 1
JAE DECREMEN_BX1
JB CONV
DECREMEN_BX1:
DEC BX
MOV AL, BYTE[NUM+BX]
SUB AL, BYTE[NUM1+BX]
MOV BYTE[FINAL+BX], AL

JMP LOOP_BRADAR1

MULTIP:
MOV BX, 0
MOV BYTE[OP],0
MOV BYTE[OP+1],0
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
MOV BX, 0
INPUT_DIDDY:
MOV AH,0X00
INT 0X16
MOV AH, 0X0E
INT 0X10

MOV BYTE[NUM+BX], AL

CMP BX, 3
JBE BX_IS_A_CATBOY
JA NEXT_INPUT_GAY
BX_IS_A_CATBOY:
INC BX
JMP INPUT_DIDDY
NEXT_INPUT_GAY:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
MOV BX, 0
IN_LOOP:
MOV AH,0X00
INT 0X16
MOV AH, 0X0E
INT 0X10

MOV BYTE[NUM1+BX], AL

CMP BX, 3
JBE INC_BX_DUMB
JA GGG
INC_BX_DUMB:
INC BX
JMP IN_LOOP
GGG:
MOV BX,0
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
BXLWA:
CMP BX, 3
JBE DIH
JA NEXT_NUMBER
DIH:
INC BX
SUB BYTE[NUM + BX], 0X30
JMP BXLWA
NEXT_NUMBER:
MOV BX, 0
KOOLAID:
CMP BX, 3
JBE INC_DUMB_LABEL_NAME
JA MUL_THEM
INC_DUMB_LABEL_NAME:
INC BX
SUB BYTE[NUM1 + BX], 0X30
JMP KOOLAID

MUL_THEM:
MOV AL, BYTE[NUM1+3]
MOV DL, 1
MUL DL
MOV BYTE[NUM1+3], AL
MOV AL, BYTE[NUM1+2]
MOV DL, 10
MUL DL
MOV BYTE[NUM1+2], AL
MOV AL, BYTE[NUM1+1]
MOV DL, 100
MUL DL
MOV  BYTE[NUM1+1],AL
MOV AL, BYTE[NUM1+0]
MOV DL, 100
MUL DL
MOV BYTE[NUM1+0], AL 
ADD AL, BYTE[NUM1+1]
ADD AL, BYTE[NUM1+2]
ADD AL, BYTE[NUM1+3]
MOV BYTE[MULTIPLA], AL
NEXT_STEP__DIDDY_BLUD:
MOV BX, 4
LOOP_BRADAR2:
CMP BX, 1
JAE DECREM_BX5
JB CONV
DECREM_BX5:
DEC BX
MOV AL, BYTE[NUM+BX]
MOV CL, BYTE[MULTIPLA]
MUL CL
ADD AL, BYTE[REMAINDER]
MOV BYTE[REMAINDER],0
MOV BYTE[FINAL+BX], AL
CMP AL, 10
JAE DIDDY
JB LOOP_BRADAR2
DIDDY:
MOV DL, AL
XOR AH, AH
MOV CH, 10
DIV CH
MOV BYTE[REMAINDER], AL
MOV BYTE[FINAL+BX], AH
JMP LOOP_BRADAR2

DIVISION:
JMP TEXT_TYPING

LOADTEXT:
MOV BX, 0
SET_LOAD_TO_LOAD:
CMP BX, WORD[PLACEHOLDER_LEN]
JA SET_BX_ABSOL_0
MOV AL, BYTE[VARTOSAVE+BX]
MOV BYTE[CURRTEXTWRITTEN + BX], AL
INC BX
JMP SET_LOAD_TO_LOAD
SET_BX_ABSOL_0:
XOR BX, BX
DOTHEDIRTYWORK:
MOV AL, BYTE[CURRTEXTWRITTEN+BX]
CMP AL, '\' 
JE NONNORM
JNE NORM1
NORM1:
MOV AH, 0X0E
INT 0X10
INC BX
CMP BX, WORD[PLACEHOLDER_LEN]
JBE DOTHEDIRTYWORK
JA ACTUALTXTL
NONNORM:
INC BX
MOV AH, 0X02
ADD DH,1
MOV DL, 0
INT 0X10
CHECKBX:
CMP BX, WORD[PLACEHOLDER_LEN]
JBE DOTHEDIRTYWORK
JA ACTUALTXTL

QUIT_TXT:
MOV BYTE[CURRTEXTWRITTEN + BX], 0
CMP BX, 0
JA DECREMENTBX
JE LOGTEXT
DECREMENTBX:
DEC BX
LOGTEXT:
MOV WORD[LEN], 19
MOV BYTE[CURRTEXT], 'Y'
MOV BYTE[CURRTEXT+1], 'O'
MOV BYTE[CURRTEXT+2], 'U'
MOV BYTE[CURRTEXT+3], ' '
MOV BYTE[CURRTEXT+4], 'E'
MOV BYTE[CURRTEXT+5], 'X'
MOV BYTE[CURRTEXT+6], 'I'
MOV BYTE[CURRTEXT+7], 'T'
MOV BYTE[CURRTEXT+8], ' '
MOV BYTE[CURRTEXT+9], 'T'
MOV BYTE[CURRTEXT+10], 'H'
MOV BYTE[CURRTEXT+11], 'E'
MOV BYTE[CURRTEXT+12], ' '
MOV BYTE[CURRTEXT+13], 'E'
MOV BYTE[CURRTEXT+14], 'D'
MOV BYTE[CURRTEXT+15], 'I'
MOV BYTE[CURRTEXT+16], 'T'
MOV BYTE[CURRTEXT+17], 'O'
MOV BYTE[CURRTEXT+18], 'R'
MOV BYTE[CURRTEXT+19], '.'

;LOG MESSAGE
MOV BX, 0
ACTSL111:
MOV AH, 0X0E
MOV AL, CURRTEXT[BX]
INT 0X10
ADD BX,1
CMP BX, WORD[LEN]
JBE ACTSL111
JAE NEWLINE

 SAVE_FROMTXT:
MOV BYTE[CURRENT_FILE_TYPE], 'A'
MOV WORD[SAVED_TEXT_LEN], BX
SAVE:
MOV BYTE[CURRENT_FL], 0
MOV BYTE[CURRENT_FL+1],0
MOV BX, 0
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
ADD DH,1
MOV DL, 0
INT 0X10
XOR BX, BX
CLEAR_LAST_FILE_LOOP:
CMP BX, 512
JBE CLEAR_BYTE
JAE NEXT_SAVE_STEP
CLEAR_BYTE:
MOV AL, BYTE[CURRTEXTWRITTEN+BX]
MOV BYTE[VARTOSAVE+BX], AL
INC BX
JMP CLEAR_LAST_FILE_LOOP
NEXT_SAVE_STEP:
MOV WORD[LEN], 18
MOV BYTE[CURRTEXT], 'E'
MOV BYTE[CURRTEXT+1], 'N'
MOV BYTE[CURRTEXT+2], 'T'
MOV BYTE[CURRTEXT+3], 'E'
MOV BYTE[CURRTEXT+4], 'R'
MOV BYTE[CURRTEXT+5], ' '
MOV BYTE[CURRTEXT+6], 'F'
MOV BYTE[CURRTEXT+7], 'I'
MOV BYTE[CURRTEXT+8], 'L'
MOV BYTE[CURRTEXT+9], 'E'
MOV BYTE[CURRTEXT+10], ' '
MOV BYTE[CURRTEXT+11], 'N'
MOV BYTE[CURRTEXT+12], 'A'
MOV BYTE[CURRTEXT+13], 'M'
MOV BYTE[CURRTEXT+14], 'E'
MOV BYTE[CURRTEXT+15], ' '
MOV BYTE[CURRTEXT+16], 'P'
MOV BYTE[CURRTEXT+17], 'L'
MOV BYTE[CURRTEXT+18], 'S'
;LOG MESSAGE
MOV BX, 0
ABC:
MOV AH, 0X0E
MOV AL, BYTE[CURRTEXT+BX]
INT 0X10
ADD BX,1
CMP BX, WORD[LEN]
JBE ABC
JAE NEWLINE_SAVE
NEWLINE_SAVE:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
ADD DH,1
MOV DL, 0
INT 0X10
XOR BX, BX
INPUT_FL:
MOV AH, 0X00
INT 0X16
MOV CH,AL


MOV BYTE[CURRENT_FL+BX], CH
INC BX
MOV AH, 0X0E
INT 0X10
CMP BX, 1
JA SET_FL1
JMP INPUT_FL
SET_FL1:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
ADD DH,1
MOV DL, 0
INT 0X10
SET_FILE_DATA:
MOV AL, BYTE[CURRENT_FL+1] ;NAME CHARACTER2
MOV BYTE[VARTOSAVE+511], AL
MOV AL, BYTE[CURRENT_FL] ;NAME CHARACTER1
MOV BYTE[VARTOSAVE+510], AL
MOV AX, WORD[SAVED_TEXT_LEN] ;LENGTH
MOV WORD[VARTOSAVE+508], AX 
MOV AL, BYTE[CURRENT_FILE_TYPE] ;TYPE
MOV BYTE[VARTOSAVE+507], AL
;LOADING CURRENT_FILES_IN_SYS TO KEEP IT UP TO DATE!
MOV AH, 0X02
MOV AL, 1
MOV CH,  79
MOV DH, 1
MOV CL, 17
MOV DL, 0X00
XOR BH, BH
MOV BX, CURRENT_FILES_IN_SYS
INT 0X13
CMP BYTE[CURRENT_FILES_IN_SYS], 0
JNE SAVE_ACTUAL
MOV BYTE[CURRENT_FILES_IN_SYS], 17
;THIS MAKES THE TOTAL OF 507 BYTES FOR THE USER TO WRITE! ALMOST HALF A KILOBYTE!
SAVE_ACTUAL:
XOR EAX, EAX
MOV AL, BYTE[CURRENT_FILES_IN_SYS]
MOV CL, 18
DIV CL
MOV CH, AL
MOV CL, AH
MOV AH, 0X03
MOV AL, 1
MOV DH, 0
MOV DL, 0X00
MOV BX, VARTOSAVE
INT 0X13
;INCREMENT FILE NUMBER, AND SAVE IT
INC BYTE[CURRENT_FILES_IN_SYS]
MOV AH, 0X03
MOV AL, 1
MOV CH,  79
MOV DH, 1
MOV CL, 17
MOV DL, 0X00
XOR BH, BH
MOV BX, CURRENT_FILES_IN_SYS
INT 0X13
;EXIT BACK TO EACH BASIC PROGRAM ACCORDING TO FILE TYPE
CMP BYTE[CURRENT_FILE_TYPE],'A'
JE HOPON



DELETE_FILE:
MOV BYTE[OP], 1
MOV BYTE[OP+1], 0
MOV WORD[X], 0
LOAD_FILE:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
ADD DH,1
MOV DL, 0
INT 0X10
MOV WORD[LEN], 18
MOV BYTE[CURRTEXT], 'E'
MOV BYTE[CURRTEXT+1], 'N'
MOV BYTE[CURRTEXT+2], 'T'
MOV BYTE[CURRTEXT+3], 'E'
MOV BYTE[CURRTEXT+4], 'R'
MOV BYTE[CURRTEXT+5], ' '
MOV BYTE[CURRTEXT+6], 'F'
MOV BYTE[CURRTEXT+7], 'I'
MOV BYTE[CURRTEXT+8], 'L'
MOV BYTE[CURRTEXT+9], 'E'
MOV BYTE[CURRTEXT+10], ' '
MOV BYTE[CURRTEXT+11], 'N'
MOV BYTE[CURRTEXT+12], 'A'
MOV BYTE[CURRTEXT+13], 'M'
MOV BYTE[CURRTEXT+14], 'E'
MOV BYTE[CURRTEXT+15], ' '
MOV BYTE[CURRTEXT+16], 'P'
MOV BYTE[CURRTEXT+17], 'L'
MOV BYTE[CURRTEXT+18], 'S'
;NEWLINE AND LOG
MOV BX, 0
ABC1:
MOV AH, 0X0E
MOV AL, BYTE[CURRTEXT+BX]
INT 0X10
ADD BX,1
CMP BX, WORD[LEN]
JBE ABC1
JAE NEWLINE_SAVE1
NEWLINE_SAVE1:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
ADD DH,1
MOV DL, 0
INT 0X10
;PREPARE INPUT
XOR BX,BX
INPUT_FL0:
MOV AH, 0X00
INT 0X16
MOV CH,AL
MOV BYTE[CURRENT_FL+BX], CH
INC BX
MOV AH, 0X0E
INT 0X10
CMP BX, 1
JA SETEFEL
JMP INPUT_FL0
SETEFEL:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
ADD DH,1
MOV DL, 0
INT 0X10
;PREPARE LOADING 
MOV BYTE[ROWS], 0
MOV BYTE[COLS], 1
MOV WORD[CURRIND], 0
LOAD_FILE_MAINLOOP:
INC WORD[CURRIND]
CMP WORD[CURRIND], 676
JA LOAD_ERR_FNX
MOV AH, 0X02
MOV AL, 1
MOV CH,  BYTE[ROWS]
MOV DH, 0
MOV CL, BYTE[COLS]
MOV DL, 0X00
MOV BX, VARTOSAVE
INT 0X13
INC BYTE[COLS]
CMP BYTE[COLS], 18
JE SET_ROWS_AND_COLS
JB SEARCH_FILE
MODE_DELETE:
MOV AH, 0X03
MOV AL, 1
MOV CH,  BYTE[ROWS]
MOV DH, 0
MOV CL, BYTE[COLS]
MOV DL, 0X00
MOV BX, X
INT 0X13
JMP TEXT_TYPING
SET_ROWS_AND_COLS:
INC BYTE[ROWS]
MOV BYTE[COLS], 1
SEARCH_FILE:
MOV AL, BYTE[CURRENT_FL]
CMP BYTE[VARTOSAVE+510], AL
JE CHAR_0_PASSED_CHECK
JNE LOAD_FILE_MAINLOOP
CHAR_0_PASSED_CHECK:
MOV AL, BYTE[CURRENT_FL+1]
CMP BYTE[VARTOSAVE+511], AL
JE FILE_MATCHES
JNE LOAD_FILE_MAINLOOP
FILE_MATCHES:
CMP BYTE[OP],1
JE MODE_DELETE
;COMPARE FILE TYPE AND OPEN ACCORDINGLY
CMP BYTE[VARTOSAVE + 507], 'A'
JE REDIRECT_TXT
JNE CHECK_NEXT_LOGIC
CHECK_NEXT_LOGIC:
;WRITE INTO THIS LABEL WHEN THERE WILL BE MORE EXISTING FILE TYPES!
REDIRECT_TXT:
MOV BX, WORD[VARTOSAVE+508]
MOV WORD[PLACEHOLDER_LEN], BX
XOR BX, BX
LOOP_SETTER:
CMP BX, WORD[PLACEHOLDER_LEN]
JAE LOADTEXT
MOV AL, BYTE[VARTOSAVE + BX]
MOV BYTE[LOAD_PLACEHOLDER+BX], AL
INC BX
JMP LOOP_SETTER


LOAD_ERR_FNX:
MOV WORD[LEN], 18
MOV BYTE[CURRTEXT], 'F'
MOV BYTE[CURRTEXT+1], 'I'
MOV BYTE[CURRTEXT+2], 'L'
MOV BYTE[CURRTEXT+3], 'E'
MOV BYTE[CURRTEXT+4], ' '
MOV BYTE[CURRTEXT+5], 'D'
MOV BYTE[CURRTEXT+6], 'O'
MOV BYTE[CURRTEXT+7], 'E'
MOV BYTE[CURRTEXT+8], 'S'
MOV BYTE[CURRTEXT+9], ' '
MOV BYTE[CURRTEXT+10], 'N'
MOV BYTE[CURRTEXT+11], 'O'
MOV BYTE[CURRTEXT+12], 'T'
MOV BYTE[CURRTEXT+13], ' '
MOV BYTE[CURRTEXT+14], 'E'
MOV BYTE[CURRTEXT+15], 'X'
MOV BYTE[CURRTEXT+16], 'I'
MOV BYTE[CURRTEXT+17], 'S'
MOV BYTE[CURRTEXT+18], 'T'
;LOG AND NEWLINE
MOV BX, 0
ABC2:
MOV AH, 0X0E
MOV AL, BYTE[CURRTEXT+BX]
INT 0X10
ADD BX,1
CMP BX, WORD[LEN]
JBE ABC2
JAE NEWLINE_SAVE2
NEWLINE_SAVE2:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
ADD DH,1
MOV DL, 0
INT 0X10
JMP TEXT_TYPING

ARROW_PRESS:
MOV AH, 0X02
SUB DH,1
MOV DL, 0
INT 0X10
JMP ACTUALTXTL
ARROW_PRESS1:
MOV AH, 0X02
ADD DH,1
MOV DL, 0
INT 0X10
JMP ACTUALTXTL

DELETE_CHAR:
CMP BX, 1
JAE DO_REM
JB ACTUALTXTL
DO_REM:
MOV BYTE[CURRTEXTWRITTEN+BX], ' '
DEC BX
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
SUB DL,1
INT 0X10
MOV AH, 0X0E
MOV AL, ' '
INT 0X10
JMP ACTUALTXTL

TEXTEDITOR:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
MOV DH, 0
MOV DL, 0
ADD BH, 1
INT 0X10
MOV BYTE[OP], 0
MOV BYTE[OP+1],0
MOV WORD[CURRIND],0
MOV BYTE[CURRTEXT],0
MOV BYTE[LEN], 19
MOV BYTE[CURRTEXT], 'W'
MOV BYTE[CURRTEXT+1], 'E'
MOV BYTE[CURRTEXT+2], 'L'
MOV BYTE[CURRTEXT+3], 'C'
MOV BYTE[CURRTEXT+4], 'O'
MOV BYTE[CURRTEXT+5], 'M'
MOV BYTE[CURRTEXT+6], 'E'
MOV BYTE[CURRTEXT+7], ' '
MOV BYTE[CURRTEXT+8], 'T'
MOV BYTE[CURRTEXT+9], 'O'
MOV BYTE[CURRTEXT+10], ' '
MOV BYTE[CURRTEXT+11], 'O'
MOV BYTE[CURRTEXT+12], 'S'
MOV BYTE[CURRTEXT+13], '_'
MOV BYTE[CURRTEXT+14], '1'
MOV BYTE[CURRTEXT+15], ' '
MOV BYTE[CURRTEXT+16], 'T'
MOV BYTE[CURRTEXT+17], 'E'
MOV BYTE[CURRTEXT+18], 'X'
MOV BYTE[CURRTEXT+19], 'T'
JMP SPECLOG

HOPON:
MOV BX, 0
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
ADD DH,1
MOV DL, 0
INT 0X10
MOV BX, 0
ACTUALTXTL:
MOV AH, 0X00
INT 0X16


;ADDITIONAL FUNCTIONS
;QUITTING:
CMP AL, 0X11
JE QUIT_TXT
;SAVING
CMP AL, 0X13
JE SAVE_FROMTXT

CMP AL, 0DH
JE ONENTER_P

CMP AH, 48H
JE ARROW_PRESS
CMP AH, 50H
JE ARROW_PRESS1
CMP AL, 08H
JE DELETE_CHAR
NOT_ARR:

REGULAR:
INC DL
MOV AH, 0X0E
INT 0X10
MOV BYTE[CURRTEXTWRITTEN + BX], AL
INC BX
JMP ACTUALTXTL
ONENTER_P:
MOV WORD[CURRTEXTWRITTEN + BX], 0X5C
INC BX
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
ADD DH,1
XOR DL, DL 
INT 0X10
JMP ACTUALTXTL

L:
MOV BX, 0
ACTSL1:
MOV AH, 0X0E
MOV AL, CURRTEXTWRITTEN[BX]
INT 0X10
ADD BX,1
CMP BX, WORD[LEN]
JBE ACTSL1
JAE ACTUALTXTL

SPECLOG:
MOV BX, 0
ACTSL:
MOV AH, 0X0E
MOV AL, CURRTEXT[BX]
INT 0X10
ADD BX,1
CMP BX, WORD[LEN]
JBE ACTSL
JAE HOPON

SPECIAL_NEWLINE:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
MOV DH, BYTE[CURRENTROW]
MOV DL, 0
INT 0X10
JMP CHECKBX


LOG:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
MOV BX,0
MOV BYTE[OP],0
MOV BYTE[OP+1], 0
ACTLOG:
MOV AH, 0X0E
MOV AL, CURRTEXT[BX]
INT 0X10
ADD BX,1
CMP BX, WORD[LEN]
JBE ACTLOG
JAE NEWLINE_USER

LOG_SYS:
MOV BX, 0
ACTLOGSYS:
MOV AH, 0X0E
MOV AL, CURRTEXT[BX]
INT 0X10
ADD BX,1
CMP BX, WORD[LEN]
JBE ACTLOGSYS
JAE NEWLINE

NEWLINE:
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
JMP TEXT_TYPING

NEWLINE_USER:
MOV BYTE[OP],0
MOV BYTE[OP+1],0
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
JMP TEXT_TYPING

TEXT_TYPING:
MOV AH, 0X00
INT 16H
INC DL
MOV BYTE[CKP], AL
MOV AH, 0X0E
INT 0X10
MOV AL, BYTE[CKP]
CMP AL, 0DH
JE PROCESS
CMP BYTE[OP], 0
JE SETZERO
JNE NEXTOPER
SETZERO:
MOV BYTE[OP], AL
JMP TEXT_TYPING
NEXTOPER:
CMP BYTE[OP+1], 0
JE DOIT
JNE TEXT_TYPING
DOIT:
MOV BYTE[OP+1], AL
JMP TEXT_TYPING

PROCESS:

CMP BYTE[OP], 'a'
JE BA
JNE BB
BA:
;CMP COMMANDS FOR CHILDS OF BRANCH A   
;A
CMP BYTE[OP+1],'d'
JE MATH
CMP BYTE[OP+1], 'a'
JE LOG
;B
CMP BYTE[OP+1], 'b'
JE SHUTDOWN
BB:
CMP BYTE[OP], 'b'
JE BB_C
JNE BC

BB_C:
;COMMAND CMPS FOR CHILDS OF B BRANCH

BC:




;BRANCH T
BT:
CMP BYTE[OP],'t'
JE BT_C
JNE BP_

BT_C:


;X
CMP BYTE[OP+1], 'x'
JE TEXTEDITOR


BP_:

;BRANCH O
CMP BYTE[OP], 'o'
JE BO_C
JNE S
;BRANCH O CHECKS
BO_C:
;P
CMP BYTE[OP+1],'p'
JE LOAD_FILE

;S
S:
CMP BYTE[OP], 's'
JE BS_C
JNE BM
BS_C:

CMP BYTE[OP+1],'u'
JE MATH
;D
BM:
CMP BYTE[OP], 'm'
JE BM_C
JNE BD
BM_C:
CMP BYTE[OP+1], 'u'
JE MATH
BD:
CMP BYTE[OP], 'd'
JE BD_C
BD_C:
CMP BYTE[OP+1], 'i'
JE DIVISION
CMP BYTE[OP+1], 'e'
JE DELETE_FILE


MOV BYTE[OP],0
MOV BYTE[OP+1],0
MOV AH, 0X02
ADD BYTE[CURRENTROW], 1
INC DH
MOV DL, 0
INT 0X10
JMP TEXT_TYPING

times 8192-($-$$) db 0 
